import json, os

base = os.path.dirname(os.path.abspath(__file__))
files = [
    ('cau-tao-tu',        'Cấu tạo từ.json'),
    ('danh-tu',           'Danh từ.json'),
    ('lien-tu',           'Liên từ.json'),
    ('tu-chi-so-luong',   'Từ chỉ số lượng.json'),
    ('tu-loai',           'Từ loại.json'),
    ('dai-tu',            'Đại từ.json'),
    ('dong-tu',           'Động từ.json'),
]

lines = ['// Auto-generated by build_data.py — do not edit manually', 'window.TOEIC_DATA = {};']
for tid, fname in files:
    path = os.path.join(base, fname)
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    lines.append(f'window.TOEIC_DATA["{tid}"] = {json.dumps(data, ensure_ascii=False, separators=(",",":"))};')

out = '\n'.join(lines)
outpath = os.path.join(base, 'data.js')
with open(outpath, 'w', encoding='utf-8') as f:
    f.write(out)
print(f'Done! data.js created: {os.path.getsize(outpath):,} bytes')
